apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: query
  ports:
    - name: http-query
      port: 16686
      targetPort: 16686
      nodePort: 30686
      protocol: TCP
